# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import video_worker_pb2 as video__worker__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in video_worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VideoWorkerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/distwan.v1.VideoWorker/Health',
                request_serializer=video__worker__pb2.HealthRequest.SerializeToString,
                response_deserializer=video__worker__pb2.HealthReply.FromString,
                _registered_method=True)
        self.GenerateFramework = channel.unary_stream(
                '/distwan.v1.VideoWorker/GenerateFramework',
                request_serializer=video__worker__pb2.FrameworkRequest.SerializeToString,
                response_deserializer=video__worker__pb2.Progress.FromString,
                _registered_method=True)
        self.RefineTile = channel.unary_stream(
                '/distwan.v1.VideoWorker/RefineTile',
                request_serializer=video__worker__pb2.RefineRequest.SerializeToString,
                response_deserializer=video__worker__pb2.Progress.FromString,
                _registered_method=True)


class VideoWorkerServicer:
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Capability negotiation + readiness (like Kakeya CapabilityService).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GenerateFramework(self, request, context):
        """Distilled-proposer low-res framework. Server-streams Progress; final msg carries mp4.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefineTile(self, request, context):
        """Full-model vid2vid refine of a framework-crop tile. Server-streams Progress.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=video__worker__pb2.HealthRequest.FromString,
                    response_serializer=video__worker__pb2.HealthReply.SerializeToString,
            ),
            'GenerateFramework': grpc.unary_stream_rpc_method_handler(
                    servicer.GenerateFramework,
                    request_deserializer=video__worker__pb2.FrameworkRequest.FromString,
                    response_serializer=video__worker__pb2.Progress.SerializeToString,
            ),
            'RefineTile': grpc.unary_stream_rpc_method_handler(
                    servicer.RefineTile,
                    request_deserializer=video__worker__pb2.RefineRequest.FromString,
                    response_serializer=video__worker__pb2.Progress.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distwan.v1.VideoWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distwan.v1.VideoWorker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VideoWorker:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distwan.v1.VideoWorker/Health',
            video__worker__pb2.HealthRequest.SerializeToString,
            video__worker__pb2.HealthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GenerateFramework(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/distwan.v1.VideoWorker/GenerateFramework',
            video__worker__pb2.FrameworkRequest.SerializeToString,
            video__worker__pb2.Progress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefineTile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/distwan.v1.VideoWorker/RefineTile',
            video__worker__pb2.RefineRequest.SerializeToString,
            video__worker__pb2.Progress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
