# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: video_worker.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'video_worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12video_worker.proto\x12\ndistwan.v1\"\x0f\n\rHealthRequest\"\x7f\n\x0bHealthReply\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61\x63kend\x18\x02 \x01(\t\x12\r\n\x05model\x18\x03 \x01(\t\x12\x0b\n\x03ops\x18\x04 \x03(\t\x12\r\n\x05ready\x18\x05 \x01(\x08\x12\x0c\n\x04note\x18\x06 \x01(\t\x12\x16\n\x0erelative_speed\x18\x07 \x01(\x02\"\x9f\x01\n\x10\x46rameworkRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x17\n\x0fnegative_prompt\x18\x02 \x01(\t\x12\r\n\x05width\x18\x03 \x01(\x05\x12\x0e\n\x06height\x18\x04 \x01(\x05\x12\x12\n\nnum_frames\x18\x05 \x01(\x05\x12\r\n\x05steps\x18\x06 \x01(\x05\x12\x0c\n\x04seed\x18\x07 \x01(\x03\x12\x12\n\ninit_image\x18\x08 \x01(\x0c\"\xa7\x01\n\rRefineRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x17\n\x0fnegative_prompt\x18\x02 \x01(\t\x12\x0b\n\x03mp4\x18\x03 \x01(\x0c\x12\r\n\x05width\x18\x04 \x01(\x05\x12\x0e\n\x06height\x18\x05 \x01(\x05\x12\x12\n\nnum_frames\x18\x06 \x01(\x05\x12\r\n\x05steps\x18\x07 \x01(\x05\x12\x10\n\x08strength\x18\x08 \x01(\x02\x12\x0c\n\x04seed\x18\t \x01(\x03\"V\n\x08Progress\x12\x0b\n\x03pct\x18\x01 \x01(\x02\x12\r\n\x05stage\x18\x02 \x01(\t\x12\x0c\n\x04\x64one\x18\x03 \x01(\x08\x12\x0b\n\x03mp4\x18\x04 \x01(\x0c\x12\x13\n\x0bgen_seconds\x18\x05 \x01(\x02\x32\xd7\x01\n\x0bVideoWorker\x12<\n\x06Health\x12\x19.distwan.v1.HealthRequest\x1a\x17.distwan.v1.HealthReply\x12I\n\x11GenerateFramework\x12\x1c.distwan.v1.FrameworkRequest\x1a\x14.distwan.v1.Progress0\x01\x12?\n\nRefineTile\x12\x19.distwan.v1.RefineRequest\x1a\x14.distwan.v1.Progress0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=34
  _globals['_HEALTHREQUEST']._serialized_end=49
  _globals['_HEALTHREPLY']._serialized_start=51
  _globals['_HEALTHREPLY']._serialized_end=178
  _globals['_FRAMEWORKREQUEST']._serialized_start=181
  _globals['_FRAMEWORKREQUEST']._serialized_end=340
  _globals['_REFINEREQUEST']._serialized_start=343
  _globals['_REFINEREQUEST']._serialized_end=510
  _globals['_PROGRESS']._serialized_start=512
  _globals['_PROGRESS']._serialized_end=598
  _globals['_VIDEOWORKER']._serialized_start=601
  _globals['_VIDEOWORKER']._serialized_end=816
# @@protoc_insertion_point(module_scope)
